# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            supercollider.js
tagline:          'The JavaScript SuperCollider client.'
description:      'SuperCollider is a platform for audio synthesis and algorithmic composition, used by musicians, artists, and researchers working with sound.'
# url:              https://crucialfelix.github.io/supercolliderjs/
# host:             https://crucialfelix.github.io
baseurl:          /supercolliderjs

author:
  name:           'Chris Sattinger'
  url:            https://twitter.com/crucialfelix

paginate:         5

# Custom vars
version:          0.13.0

github:           crucialfelix/supercolliderjs
repository:       https://github.com/crucialfelix/supercolliderjs
